[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hypatia_lib = {path = "../hypatia_lib"}
console = "0.15.1"
dialoguer = "0.10.2"