name: Web CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./web/package-lock.json
    - run: npm ci   
    - run: npm run wasm  
    - run: grep -m 1 "VITE" <(npm run dev)
    - run: npm run build
    - name: Deploy to gh-pages 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist/
